graph TD
classDef Literal fill:#f2f2f2,stroke:#000000;
classDef CRM_Entity fill:#FFFFFF,stroke:#000000;
classDef Temporal_Entity fill:#00C9E6, stroke:#000000;
classDef Type fill:#E18312, stroke:#000000;
classDef Time-Span fill:#2C9C91, stroke:#000000;
classDef Appellation fill:#FFEB7F, stroke:#000000;
classDef Place fill:#008836, stroke:#000000;
classDef Persistent_Item fill:#B266B2, stroke:#000000;
classDef Conceptual_Object fill:#FFD700, stroke:#000000;
classDef Physical_Thing fill:#D2B48C, stroke:#000000;
classDef Actor fill:#f58aad, stroke:#000000;
classDef PC_Classes fill:#4ce600, stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;

0["crm:E5_Event"]:::Temporal_Entity -->|crm:P2_has_type| 1["crm:E55_Type"]:::Type
2["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 3[xsd:dateTime]:::Literal
2["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_end_of_the_end| 4[xsd:dateTime]:::Literal
6["crm:E8_Acquisition"]:::Temporal_Entity -->|crm:P22_transferred_title_to| 7["crm:E39_Actor"]:::Actor
8["crm:E52_Time-Span"]:::Time-Span -->|crm:P82b_end_of_the_end| 9[xsd:dateTime]:::Literal
10["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P24i_changed_ownership_through| 11["crm:E8_Acquisition"]:::Temporal_Entity
10["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P12i_was_present_at| 0["crm:E5_Event"]:::Temporal_Entity
12["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 13[xsd:dateTime]:::Literal
12["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_end_of_the_end| 14[xsd:dateTime]:::Literal
15["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 16[xsd:dateTime]:::Literal
15["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_end_of_the_end| 17[xsd:dateTime]:::Literal
22["crm:E11_Modification"]:::Temporal_Entity -->|crm:P4_has_time-span| 8["crm:E52_Time-Span"]:::Time-Span
22["crm:E11_Modification"]:::Temporal_Entity -->|crm:P32_used_general_technique| 23["crm:E55_Type"]:::Type
22["crm:E11_Modification"]:::Temporal_Entity -->|crm:P2_has_type| 24["crm:E55_Type"]:::Type
6["crm:E8_Acquisition"]:::Temporal_Entity -->|crm:P129i_is_subject_of| 25["crm:E33_Linguistic_Object"]:::Conceptual_Object
10["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P24i_changed_ownership_through| 6["crm:E8_Acquisition"]:::Temporal_Entity
22["crm:E11_Modification"]:::Temporal_Entity -->|crm:P119i_is_subject_of| 27["crm:E73_Linguistic_Object"]:::Default
11["crm:E8_Acquisition"]:::Temporal_Entity -->|crm:P23_transferred_title_from| 20["crm:E39_Actor"]:::Actor
10["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P2_has_type| 33["crm:E55_type"]:::Default
6["crm:E8_Acquisition"]:::Temporal_Entity -->|crm:P115i_is_finished_by| 11["crm:E8_Acquisition"]:::Temporal_Entity
11["crm:E8_Acquisition"]:::Temporal_Entity -->|crm:P4_has_time-span| 15["crm:E52_Time-Span"]:::Time-Span
10["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P31i_was_modified_by| 22["crm:E11_Modification"]:::Temporal_Entity
22["crm:E11_Modification"]:::Temporal_Entity -->|crm:P14_carried_out_by| 30["crm:E21_Person"]:::Actor
6["crm:E8_Acquisition"]:::Temporal_Entity -->|crm:P4_has_time-span| 12["crm:E52_Time-Span"]:::Time-Span
8["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 41[xsd:dateTime]:::Literal
0["crm:E5_Event"]:::Temporal_Entity -->|crm:P4_has_time-span| 2["crm:E52_Time-Span"]:::Time-Span
