graph TD
classDef Literal fill:#f2f2f2,stroke:#000000;
classDef CRM_Entity fill:#FFFFFF,stroke:#000000;
classDef Temporal_Entity fill:#00C9E6, stroke:#000000;
classDef Type fill:#E18312, stroke:#000000;
classDef Time-Span fill:#2C9C91, stroke:#000000;
classDef Appellation fill:#FFEB7F, stroke:#000000;
classDef Place fill:#008836, stroke:#000000;
classDef Persistent_Item fill:#B266B2, stroke:#000000;
classDef Conceptual_Object fill:#FFD700, stroke:#000000;
classDef Physical_Thing fill:#D2B48C, stroke:#000000;
classDef Actor fill:#f58aad, stroke:#000000;
classDef PC_Classes fill:#4ce600, stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;

0["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P72_has_language| 1["crm:E56_Language"]:::Type
4["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P72_has_language| 5["crm:E56_Language"]:::Type
4["crm:E33_E41_Linguistic_Appellation"]:::Default -->|frbroo:R64i_was_name_used_by| 6["frbroo:F52_Name_Use_Activity"]:::Temporal_Entity
7["crm:E52_Time-Span"]:::Time-Span -->|crm:P82b_end_of_the_end| 9[xsd:dateTime]:::Literal
6["frbroo:F52_Name_Use_Activity"]:::Temporal_Entity -->|crm:P4_has_time-span| 7["crm:E52_Time-Span"]:::Time-Span
10["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P1_is_identified_by| 11["crm:E42_Identifier"]:::Appellation
0["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P190_has_symbolic_content| 13[rdfs:Literal]:::Literal
14["crm:E15_Identifier_Assignment"]:::Temporal_Entity -->|crm:P16_used_specific_object| 15["crm:E73_Information_Object"]:::Conceptual_Object
4["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P190_has_symbolic_content| 18[rdfs:Literal]:::Literal
10["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P2_has_type| 22["crm:E55_Type"]:::Type
10["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P1_is_identified_by| 0["crm:E33_E41_Linguistic_Appellation"]:::Default
4["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P2_has_type| 24["crm:E55_Type"]:::Type
10["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P2_has_type| 27["crm:E55_Type"]:::Type
22["crm:E55_Type"]:::Type -->|crm:P141i_was_assigned_by| 16["crm:E17_Type_Assignment"]:::Temporal_Entity
10["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P1_is_identified_by| 4["crm:E33_E41_Linguistic_Appellation"]:::Default
11["crm:E42_Identifier"]:::Appellation -->|crm:P37i_was_assigned_by| 14["crm:E15_Identifier_Assignment"]:::Temporal_Entity
14["crm:E15_Identifier_Assignment"]:::Temporal_Entity -->|crm:P14_carried_out_by| 42["crm:E39_Actor"]:::Actor
32["crm:E13_Attribute_Assignment"]:::Temporal_Entity -->|crm:P14_carried_out_by| 19["crm:E39_Actor"]:::Actor
22["crm:E55_Type"]:::Type -->|crm:P2_has_type| 25["crm:E55_Type"]:::Type
11["crm:E42_Identifier"]:::Appellation -->|crm:P190_has_symbolic_content| 48[rdfs:Literal]:::Literal
11["crm:E42_Identifier"]:::Appellation -->|crm:P2_has_type| 44["crm:E55_Type"]:::Type
16["crm:E17_Type_Assignment"]:::Temporal_Entity -->|crm:P14_carried_out_by| 35["crm:E39_Actor"]:::Actor
7["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 49[xsd:dateTime]:::Literal
4["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P141i_was_assigned_by| 32["crm:E13_Attribute_Assignment"]:::Temporal_Entity
10["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P2_has_type| 30["crm:E55_type"]:::Default
0["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P2_has_type| 2["crm:E55_Type"]:::Type
