graph TD
classDef Literal fill:#f2f2f2,stroke:#000000;
classDef CRM_Entity fill:#FFFFFF,stroke:#000000;
classDef Temporal_Entity fill:#00C9E6, stroke:#000000;
classDef Type fill:#E18312, stroke:#000000;
classDef Time-Span fill:#2C9C91, stroke:#000000;
classDef Appellation fill:#FFEB7F, stroke:#000000;
classDef Place fill:#008836, stroke:#000000;
classDef Persistent_Item fill:#B266B2, stroke:#000000;
classDef Conceptual_Object fill:#FFD700, stroke:#000000;
classDef Physical_Thing fill:#D2B48C, stroke:#000000;
classDef Actor fill:#f58aad, stroke:#000000;
classDef PC_Classes fill:#4ce600, stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;

0["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P190_has_symbolic_content| 1[rdfs:Literal]:::Literal
2["crm:E55_Type"]:::Type -->|crm:P141i_was_assigned_by| 3["crm:E17_Type_Assignment"]:::Temporal_Entity
6["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P1_is_identified_by| 7["crm:E42_Identifier"]:::Appellation
8["crm:E15_Identifier_Assignment"]:::Temporal_Entity -->|crm:P16_used_specific_object| 9["crm:E73_Information_Object"]:::Conceptual_Object
6["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P2_has_type| 11["crm:E55_type"]:::Default
8["crm:E15_Identifier_Assignment"]:::Temporal_Entity -->|crm:P14_carried_out_by| 12["crm:E39_Actor"]:::Actor
2["crm:E55_Type"]:::Type -->|crm:P2_has_type| 13["crm:E55_Type"]:::Type
14["crm:E33_E41_Linguistic_Appellation"]:::Default -->|frbroo:R64i_was_name_used_by| 15["frbroo:F52_Name_Use_Activity"]:::Temporal_Entity
3["crm:E17_Type_Assignment"]:::Temporal_Entity -->|crm:P14_carried_out_by| 16["crm:E39_Actor"]:::Actor
0["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P72_has_language| 20["crm:E56_Language"]:::Type
7["crm:E42_Identifier"]:::Appellation -->|crm:P190_has_symbolic_content| 22[rdfs:Literal]:::Literal
14["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P2_has_type| 24["crm:E55_Type"]:::Type
14["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P72_has_language| 25["crm:E56_Language"]:::Type
14["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P141i_was_assigned_by| 27["crm:E13_Attribute_Assignment"]:::Temporal_Entity
0["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P2_has_type| 4["crm:E55_Type"]:::Type
27["crm:E13_Attribute_Assignment"]:::Temporal_Entity -->|crm:P14_carried_out_by| 37["crm:E39_Actor"]:::Actor
7["crm:E42_Identifier"]:::Appellation -->|crm:P37i_was_assigned_by| 8["crm:E15_Identifier_Assignment"]:::Temporal_Entity
31["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 38[xsd:dateTime]:::Literal
6["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P1_is_identified_by| 14["crm:E33_E41_Linguistic_Appellation"]:::Default
6["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P2_has_type| 33["crm:E55_Type"]:::Type
14["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P190_has_symbolic_content| 42[rdfs:Literal]:::Literal
31["crm:E52_Time-Span"]:::Time-Span -->|crm:P82b_end_of_the_end| 46[xsd:dateTime]:::Literal
6["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P2_has_type| 2["crm:E55_Type"]:::Type
6["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P1_is_identified_by| 0["crm:E33_E41_Linguistic_Appellation"]:::Default
7["crm:E42_Identifier"]:::Appellation -->|crm:P2_has_type| 29["crm:E55_Type"]:::Type
15["frbroo:F52_Name_Use_Activity"]:::Temporal_Entity -->|crm:P4_has_time-span| 31["crm:E52_Time-Span"]:::Time-Span
