graph TD
classDef Literal fill:#f2f2f2,stroke:#000000;
classDef CRM_Entity fill:#FFFFFF,stroke:#000000;
classDef Temporal_Entity fill:#00C9E6, stroke:#000000;
classDef Type fill:#E18312, stroke:#000000;
classDef Time-Span fill:#2C9C91, stroke:#000000;
classDef Appellation fill:#FFEB7F, stroke:#000000;
classDef Place fill:#008836, stroke:#000000;
classDef Persistent_Item fill:#B266B2, stroke:#000000;
classDef Conceptual_Object fill:#FFD700, stroke:#000000;
classDef Physical_Thing fill:#D2B48C, stroke:#000000;
classDef Actor fill:#f58aad, stroke:#000000;
classDef PC_Classes fill:#4ce600, stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;

0["crm:E11_Modification"]:::Temporal_Entity -->|crm:P2_has_type| 1["crm:E55_Type"]:::Type
0["crm:E11_Modification"]:::Temporal_Entity -->|crm:P32_used_general_technique| 4["crm:E55_Type"]:::Type
7["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 8[xsd:dateTime]:::Literal
0["crm:E11_Modification"]:::Temporal_Entity -->|crm:P4_has_time-span| 9["crm:E52_Time-Span"]:::Time-Span
10["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 11[xsd:dateTime]:::Literal
5["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P12i_was_present_at| 12["crm:E5_Event"]:::Temporal_Entity
9["crm:E52_Time-Span"]:::Time-Span -->|crm:P82b_end_of_the_end| 14[xsd:dateTime]:::Literal
0["crm:E11_Modification"]:::Temporal_Entity -->|crm:P119i_is_subject_of| 15["crm:E73_Linguistic_Object"]:::Default
19["crm:E8_Acquisition"]:::Temporal_Entity -->|crm:P115i_is_finished_by| 20["crm:E8_Acquisition"]:::Temporal_Entity
12["crm:E5_Event"]:::Temporal_Entity -->|crm:P2_has_type| 22["crm:E55_Type"]:::Type
12["crm:E5_Event"]:::Temporal_Entity -->|crm:P4_has_time-span| 24["crm:E52_Time-Span"]:::Time-Span
19["crm:E8_Acquisition"]:::Temporal_Entity -->|crm:P22_transferred_title_to| 2["crm:E39_Actor"]:::Actor
5["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P31i_was_modified_by| 0["crm:E11_Modification"]:::Temporal_Entity
9["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 25[xsd:dateTime]:::Literal
19["crm:E8_Acquisition"]:::Temporal_Entity -->|crm:P129i_is_subject_of| 26["crm:E33_Linguistic_Object"]:::Conceptual_Object
24["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_end_of_the_end| 27[xsd:dateTime]:::Literal
7["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_end_of_the_end| 28[xsd:dateTime]:::Literal
0["crm:E11_Modification"]:::Temporal_Entity -->|crm:P14_carried_out_by| 16["crm:E21_Person"]:::Actor
20["crm:E8_Acquisition"]:::Temporal_Entity -->|crm:P23_transferred_title_from| 32["crm:E39_Actor"]:::Actor
10["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_end_of_the_end| 36[xsd:dateTime]:::Literal
19["crm:E8_Acquisition"]:::Temporal_Entity -->|crm:P4_has_time-span| 7["crm:E52_Time-Span"]:::Time-Span
5["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P24i_changed_ownership_through| 19["crm:E8_Acquisition"]:::Temporal_Entity
24["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 41[xsd:dateTime]:::Literal
5["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P24i_changed_ownership_through| 20["crm:E8_Acquisition"]:::Temporal_Entity
20["crm:E8_Acquisition"]:::Temporal_Entity -->|crm:P4_has_time-span| 10["crm:E52_Time-Span"]:::Time-Span
5["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P2_has_type| 37["crm:E55_type"]:::Default
