graph TD
classDef Literal fill:#f2f2f2,stroke:#000000;
classDef CRM_Entity fill:#FFFFFF,stroke:#000000;
classDef Temporal_Entity fill:#00C9E6, stroke:#000000;
classDef Type fill:#E18312, stroke:#000000;
classDef Time-Span fill:#2C9C91, stroke:#000000;
classDef Appellation fill:#FFEB7F, stroke:#000000;
classDef Place fill:#008836, stroke:#000000;
classDef Persistent_Item fill:#B266B2, stroke:#000000;
classDef Conceptual_Object fill:#FFD700, stroke:#000000;
classDef Physical_Thing fill:#D2B48C, stroke:#000000;
classDef Actor fill:#f58aad, stroke:#000000;
classDef PC_Classes fill:#4ce600, stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;

8["crm:E21_Person"]:::Actor -->|crm:P1_is_identified_by| 9["crm:E33_E41_Linguistic_Appellation"]:::Default
9["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P190_has_symbolic_content| 10[rdfs:Literal]:::Literal
8["crm:E21_Person"]:::Actor -->|crm:P1_is_identified_by| 4["crm:E33_E41_Linguistic_Appellation"]:::Default
9["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P72_has_language| 0["crm:E56_Language"]:::Type
13["crm:E42_Identifier"]:::Appellation -->|crm:P190_has_symbolic_content| 14[rdfs:Literal]:::Literal
17["crm:E15_Identifier_Assignment"]:::Temporal_Entity -->|crm:P16_used_specific_object| 6["crm:E73_Information_Object"]:::Conceptual_Object
22["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P2_has_type| 23["crm:E55_Type"]:::Type
17["crm:E15_Identifier_Assignment"]:::Temporal_Entity -->|crm:P14_carried_out_by| 20["crm:E39_Actor"]:::Actor
8["crm:E21_Person"]:::Actor -->|crm:P2_has_type| 27["crm:E55_Type"]:::Type
13["crm:E42_Identifier"]:::Appellation -->|crm:P37i_was_assigned_by| 17["crm:E15_Identifier_Assignment"]:::Temporal_Entity
29["frbroo:F52_Name_Use_Activity"]:::Temporal_Entity -->|crm:P4_has_time-span| 30["crm:E52_Time-Span"]:::Time-Span
13["crm:E42_Identifier"]:::Appellation -->|crm:P2_has_type| 33["crm:E55_Type"]:::Type
4["crm:E33_E41_Linguistic_Appellation"]:::Default -->|frbroo:R64i_was_name_used_by| 29["frbroo:F52_Name_Use_Activity"]:::Temporal_Entity
30["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 36[xsd:dateTime]:::Literal
4["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P2_has_type| 15["crm:E55_Type"]:::Type
30["crm:E52_Time-Span"]:::Time-Span -->|crm:P82b_end_of_the_end| 40[xsd:dateTime]:::Literal
9["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P106_is_composed_of| 22["crm:E33_E41_Linguistic_Appellation"]:::Default
41["crm:E13_Attribute_Assignment"]:::Temporal_Entity -->|crm:P16_used_specific_object| 18["crm:E73_Information_Object"]:::Conceptual_Object
9["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P2_has_type| 11["crm:E55_Type"]:::Type
41["crm:E13_Attribute_Assignment"]:::Temporal_Entity -->|crm:P14_carried_out_by| 2["crm:E39_Actor"]:::Actor
4["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P190_has_symbolic_content| 44[rdfs:Literal]:::Literal
8["crm:E21_Person"]:::Actor -->|crm:P1_is_identified_by| 13["crm:E42_Identifier"]:::Appellation
4["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P72_has_language| 25["crm:E56_Language"]:::Type
4["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P141i_was_assigned_by| 41["crm:E13_Attribute_Assignment"]:::Temporal_Entity
