graph TD
classDef Literal fill:#f2f2f2,stroke:#000000;
classDef CRM_Entity fill:#FFFFFF,stroke:#000000;
classDef Temporal_Entity fill:#00C9E6, stroke:#000000;
classDef Type fill:#E18312, stroke:#000000;
classDef Time-Span fill:#2C9C91, stroke:#000000;
classDef Appellation fill:#FFEB7F, stroke:#000000;
classDef Place fill:#008836, stroke:#000000;
classDef Persistent_Item fill:#B266B2, stroke:#000000;
classDef Conceptual_Object fill:#FFD700, stroke:#000000;
classDef Physical_Thing fill:#D2B48C, stroke:#000000;
classDef Actor fill:#f58aad, stroke:#000000;
classDef PC_Classes fill:#4ce600, stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;

0["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crmdig:L54_is_same-as| 2["crm:E1_CRM_Entity"]:::CRM_Entity
0["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P138i_has_representation| 3["crmdig:D9_Data_Object<br>crm:E36_Visual_Item"]:::Multi
6["crm:E33_Linguistic_Object"]:::Conceptual_Object -->|crm:P190_has_symbolic_content| 7[rdfs:Literal]:::Literal
6["crm:E33_Linguistic_Object"]:::Conceptual_Object -->|crm:P106i_forms_part_of| 8["crm:E33_Linguistic_Object"]:::Conceptual_Object
0["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P2_has_type| 11["crm:E55_type"]:::Default
6["crm:E33_Linguistic_Object"]:::Conceptual_Object -->|crm:P2_has_type| 12["crm:E55_Type"]:::Type
0["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P129i_is_subject_of| 6["crm:E33_Linguistic_Object"]:::Conceptual_Object
