graph TD
classDef Literal fill:#f2f2f2,stroke:#000000;
classDef CRM_Entity fill:#FFFFFF,stroke:#000000;
classDef Temporal_Entity fill:#00C9E6, stroke:#000000;
classDef Type fill:#E18312, stroke:#000000;
classDef Time-Span fill:#2C9C91, stroke:#000000;
classDef Appellation fill:#FFEB7F, stroke:#000000;
classDef Place fill:#008836, stroke:#000000;
classDef Persistent_Item fill:#B266B2, stroke:#000000;
classDef Conceptual_Object fill:#FFD700, stroke:#000000;
classDef Physical_Thing fill:#D2B48C, stroke:#000000;
classDef Actor fill:#f58aad, stroke:#000000;
classDef PC_Classes fill:#4ce600, stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;

4["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P140i_was_attributed_by| 6["crm:E13_Attribute_Assignment"]:::Temporal_Entity
4["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P50_current_keeper| 11["crm:E39_Actor"]:::Actor
4["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P108i_was_produced_by| 9["crm:E12_Production"]:::Temporal_Entity
6["crm:E13_Attribute_Assignment"]:::Temporal_Entity -->|crm:P2_has_type| 0["crm:E55_Type"]:::Type
6["crm:E13_Attribute_Assignment"]:::Temporal_Entity -->|crm:P141_assigned| 7["crm:E74_Group"]:::Actor
4["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P52_has_current_owner| 2["crm:E39_Actor"]:::Actor
9["crm:E12_Production"]:::Temporal_Entity -->|crm:P01i_is_domain_of| 16["crm:PC14_carried_out_by"]:::PC_Classes
4["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P2_has_type| 14["crm:E55_type"]:::Default
16["crm:PC14_carried_out_by"]:::PC_Classes -->|crm:P14.1_in_the_role_of| 17["crm:E55_Type"]:::Type
16["crm:PC14_carried_out_by"]:::PC_Classes -->|crm:P02_has_range| 19["crm:E39_Actor"]:::Actor
