graph TD
classDef Literal fill:#f2f2f2,stroke:#000000;
classDef CRM_Entity fill:#FFFFFF,stroke:#000000;
classDef Temporal_Entity fill:#00C9E6, stroke:#000000;
classDef Type fill:#E18312, stroke:#000000;
classDef Time-Span fill:#2C9C91, stroke:#000000;
classDef Appellation fill:#FFEB7F, stroke:#000000;
classDef Place fill:#008836, stroke:#000000;
classDef Persistent_Item fill:#B266B2, stroke:#000000;
classDef Conceptual_Object fill:#FFD700, stroke:#000000;
classDef Physical_Thing fill:#D2B48C, stroke:#000000;
classDef Actor fill:#f58aad, stroke:#000000;
classDef PC_Classes fill:#4ce600, stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;

6["frbroo:F52_Name_Use_Activity"]:::Temporal_Entity -->|crm:P140_assigned_attribute_to| 7["crm:E4_Period"]:::Temporal_Entity
8["crm:E17_Type_Assignment"]:::Temporal_Entity -->|crm:P42_assigned| 9["crm:E55_Type"]:::Type
2["crm:E93_Presence"]:::CRM_Entity -->|crm:P10i_contains| 6["frbroo:F52_Name_Use_Activity"]:::Temporal_Entity
16["crm:E53_Place"]:::Place -->|crm:P89_falls_within| 12["crm:E53_Place"]:::Place
16["crm:E53_Place"]:::Place -->|crm:P89i_contains| 14["crm:E53_Place"]:::Place
10["crm:E53_Place"]:::Place -->|crm:P168_place_is_defined_by| 17[rdfs:Literal]:::Literal
18["crm:E53_Place"]:::Place -->|crm:P168_place_is_defined_by| 19[rdfs:Literal]:::Literal
8["crm:E17_Type_Assignment"]:::Temporal_Entity -->|crm:P41_classified| 7["crm:E4_Period"]:::Temporal_Entity
2["crm:E93_Presence"]:::CRM_Entity -->|crm:P161i_is_spatial_projection_of| 18["crm:E53_Place"]:::Place
0["crm:E52_Time-Span"]:::Time-Span -->|crm:P82b_end_of_the_end| 21[xsd:dateTime]:::Literal
6["frbroo:F52_Name_Use_Activity"]:::Temporal_Entity -->|frbroo:R64_used_name| 22["crm:E41_Appellation"]:::Appellation
22["crm:E41_Appellation"]:::Appellation -->|crm:P190_has_symbolic_content| 23[rdfs:Literal]:::Literal
2["crm:E93_Presence"]:::CRM_Entity -->|crm:P164_is_temporally_specified_by| 0["crm:E52_Time-Span"]:::Time-Span
2["crm:E93_Presence"]:::CRM_Entity -->|crm:P10i_contains| 8["crm:E17_Type_Assignment"]:::Temporal_Entity
0["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 27[xsd:dateTime]:::Literal
2["crm:E93_Presence"]:::CRM_Entity -->|crm:P10_falls_within| 4["crm:E4_Period"]:::Temporal_Entity
4["crm:E4_Period"]:::Temporal_Entity -->|crm:P161_has_spatial_projection| 10["crm:E53_Place"]:::Place
7["crm:E4_Period"]:::Temporal_Entity -->|crm:P166i_had_presence| 2["crm:E93_Presence"]:::CRM_Entity
16["crm:E53_Place"]:::Place -->|crm:P161i_is_spatial_projection_of| 7["crm:E4_Period"]:::Temporal_Entity
