graph TD
classDef Literal fill:#f2f2f2,stroke:#000000;
classDef CRM_Entity fill:#FFFFFF,stroke:#000000;
classDef Temporal_Entity fill:#00C9E6, stroke:#000000;
classDef Type fill:#E18312, stroke:#000000;
classDef Time-Span fill:#2C9C91, stroke:#000000;
classDef Appellation fill:#FFEB7F, stroke:#000000;
classDef Place fill:#008836, stroke:#000000;
classDef Persistent_Item fill:#B266B2, stroke:#000000;
classDef Conceptual_Object fill:#FFD700, stroke:#000000;
classDef Physical_Thing fill:#D2B48C, stroke:#000000;
classDef Actor fill:#f58aad, stroke:#000000;
classDef PC_Classes fill:#4ce600, stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;

6["crm:E53_Place"]:::Place -->|crm:P89i_contains| 2["crm:E53_Place"]:::Place
7["crm:E93_Presence"]:::CRM_Entity -->|crm:P10i_contains| 8["crm:E17_Type_Assignment"]:::Temporal_Entity
8["crm:E17_Type_Assignment"]:::Temporal_Entity -->|crm:P41_classified| 9["crm:E4_Period"]:::Temporal_Entity
11["crm:E4_Period"]:::Temporal_Entity -->|crm:P161_has_spatial_projection| 12["crm:E53_Place"]:::Place
14["crm:E41_Appellation"]:::Appellation -->|crm:P190_has_symbolic_content| 15[rdfs:Literal]:::Literal
6["crm:E53_Place"]:::Place -->|crm:P89_falls_within| 16["crm:E53_Place"]:::Place
9["crm:E4_Period"]:::Temporal_Entity -->|crm:P166i_had_presence| 7["crm:E93_Presence"]:::CRM_Entity
7["crm:E93_Presence"]:::CRM_Entity -->|crm:P164_is_temporally_specified_by| 17["crm:E52_Time-Span"]:::Time-Span
17["crm:E52_Time-Span"]:::Time-Span -->|crm:P82b_end_of_the_end| 18[xsd:dateTime]:::Literal
17["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 19[xsd:dateTime]:::Literal
7["crm:E93_Presence"]:::CRM_Entity -->|crm:P10i_contains| 4["frbroo:F52_Name_Use_Activity"]:::Temporal_Entity
4["frbroo:F52_Name_Use_Activity"]:::Temporal_Entity -->|frbroo:R64_used_name| 14["crm:E41_Appellation"]:::Appellation
8["crm:E17_Type_Assignment"]:::Temporal_Entity -->|crm:P42_assigned| 0["crm:E55_Type"]:::Type
7["crm:E93_Presence"]:::CRM_Entity -->|crm:P161i_is_spatial_projection_of| 20["crm:E53_Place"]:::Place
6["crm:E53_Place"]:::Place -->|crm:P161i_is_spatial_projection_of| 9["crm:E4_Period"]:::Temporal_Entity
7["crm:E93_Presence"]:::CRM_Entity -->|crm:P10_falls_within| 11["crm:E4_Period"]:::Temporal_Entity
12["crm:E53_Place"]:::Place -->|crm:P168_place_is_defined_by| 27[rdfs:Literal]:::Literal
20["crm:E53_Place"]:::Place -->|crm:P168_place_is_defined_by| 29[rdfs:Literal]:::Literal
4["frbroo:F52_Name_Use_Activity"]:::Temporal_Entity -->|crm:P140_assigned_attribute_to| 9["crm:E4_Period"]:::Temporal_Entity
