graph TD
classDef Literal fill:#f2f2f2,stroke:#000000;
classDef CRM_Entity fill:#FFFFFF,stroke:#000000;
classDef Temporal_Entity fill:#00C9E6, stroke:#000000;
classDef Type fill:#E18312, stroke:#000000;
classDef Time-Span fill:#2C9C91, stroke:#000000;
classDef Appellation fill:#FFEB7F, stroke:#000000;
classDef Place fill:#008836, stroke:#000000;
classDef Persistent_Item fill:#B266B2, stroke:#000000;
classDef Conceptual_Object fill:#FFD700, stroke:#000000;
classDef Physical_Thing fill:#D2B48C, stroke:#000000;
classDef Actor fill:#f58aad, stroke:#000000;
classDef PC_Classes fill:#4ce600, stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;

0["crmdig:D7_Digital_Machine_Event"]:::Temporal_Entity -->|crm:P2_has_type| 1["crm:E55_Type"]:::Type
2["crmdig:D1_Digital_Object"]:::Conceptual_Object -->|crmdig:L11i_was_output_of| 0["crmdig:D7_Digital_Machine_Event"]:::Temporal_Entity
3["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 4[xsd:dateTime]:::Literal
8["crmdig:D7_Digital_Machine_Event"]:::Temporal_Entity -->|crm:P2_has_type| 5["crm:E55_Type"]:::Type
3["crm:E52_Time-Span"]:::Time-Span -->|crm:P82b_end_of_the_end| 13[xsd:dateTime]:::Literal
8["crmdig:D7_Digital_Machine_Event"]:::Temporal_Entity -->|crm:P4_has_time-span| 3["crm:E52_Time-Span"]:::Time-Span
0["crmdig:D7_Digital_Machine_Event"]:::Temporal_Entity -->|crm:P4_has_time-span| 15["crm:E52_Time-Span"]:::Time-Span
0["crmdig:D7_Digital_Machine_Event"]:::Temporal_Entity -->|crm:P2_has_type| 16["crm:E55_Type"]:::Type
2["crmdig:D1_Digital_Object"]:::Conceptual_Object -->|crmdig:L11i_was_output_of| 8["crmdig:D7_Digital_Machine_Event"]:::Temporal_Entity
15["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 19[xsd:dateTime]:::Literal
15["crm:E52_Time-Span"]:::Time-Span -->|crm:P82b_end_of_the_end| 22[xsd:dateTime]:::Literal
